/*

View

*/

CREATE VIEW viw_SandPvGold
WITH SCHEMABINDING
AS

SELECT S.Date
	, s.Price SPrice
	, g.Price GPrice
	, s.price/g.Price StoGRatio
FROM SPYHistoricalData s
	INNER JOIN GLDHistoricalData g ON s.Date = g.Date



/*

Clustered Index

*/

SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF


GO

CREATE UNIQUE CLUSTERED INDEX [IX_Date] ON [dbo].[viw_SandPvGold]
(
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

/*

Non-Clustered Index

*/

SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF


GO

CREATE NONCLUSTERED INDEX [IX_Ratio] ON [dbo].[viw_SandPvGold]
(
	[StoGRatio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO
