-- Straight values
SELECT BINARY_CHECKSUM('dog')
SELECT BINARY_CHECKSUM('DOG')
SELECT BINARY_CHECKSUM('Dog')
SELECT BINARY_CHECKSUM('dOg')
SELECT BINARY_CHECKSUM('doG')
SELECT BINARY_CHECKSUM('DOg')
SELECT BINARY_CHECKSUM('dOG')
SELECT BINARY_CHECKSUM('DoG')
SELECT BINARY_CHECKSUM(1)
SELECT BINARY_CHECKSUM(1.0)
SELECT BINARY_CHECKSUM(2)
SELECT BINARY_CHECKSUM(2.0)


-- INT Delta example

CREATE TABLE Durkah( 
A INT
)

INSERT INTO Durkah 
VALUES (1)
	, (2)
	, (3)

SELECT ROW_NUMBER() OVER(ORDER BY BINARY_CHECKSUM(*)) AS ID 
	, BINARY_CHECKSUM(*) AS BinaryCheckSumOne
INTO #Caught
FROM Durkah

UPDATE Durkah 
SET A = 4

;WITH Durk AS(
	SELECT ROW_NUMBER() OVER(ORDER BY BINARY_CHECKSUM(*)) AS ID 
		, BINARY_CHECKSUM(*) AS BinaryCheckSumTwo
	FROM Durkah
)
SELECT d.BinaryCheckSumTwo - c.BinaryCheckSumOne AS [ChangeInIntValues]
FROM Durk d
	INNER JOIN #Caught c ON d.ID = c.ID


DROP TABLE Durkah
DROP TABLE #Caught
