/*

Compare the column counts for tables in different environments/databases

*/

DECLARE @CompCounts TABLE(
	TableName VARCHAR(250),
	TableOneColumnCount INT,
	TableTwoColumnCount INT
)

INSERT INTO @CompCounts (TableName,TableOneColumnCount)
SELECT TABLE_NAME TableOne
	, COUNT(COLUMN_NAME) AS [ColumnCount]
FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK)
GROUP BY TABLE_NAME

;WITH GG AS(
	SELECT TABLE_NAME TN
		, COUNT(COLUMN_NAME) CC
	FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK)
	GROUP BY TABLE_NAME
)
UPDATE @CompCounts
SET TableTwoColumnCount = GG.CC FROM GG
WHERE GG.TN = TableName

SELECT *
FROM @CompCounts

/*

-- For finding tables that don't match:
SELECT *
FROM @CompCounts
WHERE TableOneColumnCount <> TableTwoColumnCount

-- Data Type:
SELECT t1.TABLE_NAME
	, t1.COLUMN_NAME
	, t2.TABLE_NAME
	, t2.COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS t1
	INNER JOIN INFORMATION_SCHEMA.COLUMNS t2 ON t1.TABLE_NAME = t2.TABLE_NAME AND t1.COLUMN_NAME = t2.COLUMN_NAME
WHERE t1.ORDINAL_POSITION <> t2.ORDINAL_POSITION
	OR t1.COLUMN_DEFAULT <> t2.COLUMN_DEFAULT
	OR t1.IS_NULLABLE <> t2.IS_NULLABLE
	OR t1.DATA_TYPE <> t2.DATA_TYPE
	OR t1.CHARACTER_MAXIMUM_LENGTH <> t2.CHARACTER_MAXIMUM_LENGTH
	OR t1.CHARACTER_OCTET_LENGTH <> t2.CHARACTER_OCTET_LENGTH
	OR t1.NUMERIC_PRECISION <> t2.NUMERIC_PRECISION
	OR t1.NUMERIC_PRECISION_RADIX <> t2.NUMERIC_PRECISION_RADIX
	OR t1.NUMERIC_SCALE <> t2.NUMERIC_SCALE
	OR t1.DATETIME_PRECISION <> t2.DATETIME_PRECISION
	OR t1.CHARACTER_SET_CATALOG <> t2.CHARACTER_SET_CATALOG
	OR t1.CHARACTER_SET_SCHEMA <> t2.CHARACTER_SET_SCHEMA
	OR t1.CHARACTER_SET_NAME <> t2.CHARACTER_SET_NAME
	OR t1.COLLATION_CATALOG <> t2.COLLATION_CATALOG
	OR t1.COLLATION_SCHEMA <> t2.COLLATION_SCHEMA
	OR t1.COLLATION_NAME <> t2.COLLATION_NAME
	OR t1.DOMAIN_CATALOG <> t2.DOMAIN_CATALOG
	OR t1.DOMAIN_SCHEMA <> t2.DOMAIN_SCHEMA
	OR t1.DOMAIN_NAME <> t2.DOMAIN_NAME

*/
