CREATE DATABASE [AdminExamples]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdminExamples', FILENAME = N'C:\Data\admin.mdf' , SIZE = 4096KB , MAXSIZE = 102400KB , FILEGROWTH = 25600KB )
 LOG ON 
( NAME = N'AdminExamples_log', FILENAME = N'C:\Log\admin_log.ldf' , SIZE = 1024KB , MAXSIZE = 102400KB , FILEGROWTH = 25600KB )
GO
ALTER DATABASE [AdminExamples] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [AdminExamples] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdminExamples] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AdminExamples] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AdminExamples] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AdminExamples] SET ARITHABORT OFF 
GO
ALTER DATABASE [AdminExamples] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdminExamples] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [AdminExamples] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdminExamples] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdminExamples] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdminExamples] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdminExamples] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AdminExamples] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdminExamples] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AdminExamples] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdminExamples] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AdminExamples] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdminExamples] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdminExamples] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdminExamples] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AdminExamples] SET  READ_WRITE 
GO
ALTER DATABASE [AdminExamples] SET RECOVERY FULL 
GO
ALTER DATABASE [AdminExamples] SET  MULTI_USER 
GO
ALTER DATABASE [AdminExamples] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AdminExamples] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [AdminExamples]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [AdminExamples] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

BACKUP DATABASE TestDatabase
TO DISK = 'E:\AdminExamples.BAK'

RESTORE VERIFYONLY
FROM DISK = 'E:\AdminExamples.BAK'
