USE Application
GO

CREATE TABLE BasicVerification(
	VerificationID BIGINT IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NULL,
	MiddleInitial VARCHAR(1) NULL,
	LastName VARCHAR(50) NULL,
	PhoneNumber VARCHAR(20) NULL,
	StreetAddress VARCHAR(150) NULL,
	City VARCHAR(50) NULL,
	State VARCHAR(2) NULL,
	ZipCode VARCHAR(10) NULL,
	SSN VARCHAR(11) NULL,
	BusinessName VARCHAR(100) NULL,
	EmployerName VARCHAR(100) NULL,
	MonthlyGrossIncome DECIMAL(20,2) NULL
)

CREATE TABLE BasicVerificationStage(
	FirstName VARCHAR(100) NULL,
	MiddleInitial VARCHAR(100) NULL,
	LastName VARCHAR(100) NULL,
	PhoneNumber VARCHAR(100) NULL,
	StreetAddress VARCHAR(100) NULL,
	City VARCHAR(100) NULL,
	State VARCHAR(100) NULL,
	ZipCode VARCHAR(100) NULL,
	SSN VARCHAR(100) NULL,
	BusinessName VARCHAR(100) NULL,
	EmployerName VARCHAR(100) NULL,
	MonthlyGrossIncome VARCHAR(100) NULL,
	Valid BIT DEFAULT 0,
	InvalidReason VARCHAR(500) NULL
)